/* ******************************************
                 *** START***
****************************************** */

import 'package:flutter/material.dart';
import 'package:weather_app/screens/home_page.dart';

class LAutocomplete extends StatefulWidget {
  const LAutocomplete({super.key});

  @override
  State<LAutocomplete> createState() => _LAutocompleteState();
}

class _LAutocompleteState extends State<LAutocomplete> {
  List<String> options = [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Ahmedabad',
    'Chennai',
    'Kolkata',
    'Surat',
    'Pune',
    'Jaipur',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
    'Thane',
    'Bhopal',
    'Visakhapatnam',
    'Pimpri-Chinchwad',
    'Patna',
    'Vadodara',
    'Ghaziabad',
    'Ludhiana',
    'Agra',
    'Nashik',
    'Faridabad',
    'Meerut',
    'Rajkot',
    'Kalyan-Dombivli',
    'Vasai-Virar',
    'Varanasi',
    'Srinagar',
    'Aurangabad',
    'Dhanbad',
    'Amritsar',
    'Navi Mumbai',
    'Allahabad',
    'Howrah',
    'Gwalior',
    'Jabalpur',
    'Coimbatore',
    'Vijayawada',
    'Jodhpur',
    'Madurai',
    'Raipur',
    'Chandigarh',
    'Guntur',
    'Guwahati',
    'Solapur',
    'Hubli-Dharwad',
    'Mysuru',
    'Tiruchirappalli',
    'Salem',
    'Kota',
    'Bhubaneswar',
    'Aligarh',
    'Bareilly',
    'Moradabad',
    'Bhiwandi',
    'Raipur',
    'Gorakhpur',
    'Bikaner',
    'Amravati',
    'Jamshedpur',
    'Bhilai',
    'Warangal',
    'Cuttack',
    'Firozabad',
    'Kochi',
    'Bhavnagar',
    'Dehradun',
    'Durgapur',
    'Asansol',
    'Nanded',
    'Kolhapur',
    'Ajmer',
    'Gulbarga',
    'Jamnagar',
    'Ujjain',
    'Loni',
    'Jhansi',
    'Siliguri',
    'Nellore',
    'Jammu',
    'Belagavi',
    'Raurkela',
    'Mangalore',
    'Tirunelveli',
    'Malegaon',
    'Gaya',
    'Thiruvananthapuram',
    'Udaipur',
    'Bilaspur',
    'Shahjahanpur',
    'Kurnool',
    'Amravati',
    'Nizamabad',
    'Muzaffarpur',
    'Ajmer',
    'Kadapa',
    'Kakinada',
    'Nizhny Novgorod',
    'Voronezh',
    'Volgograd',
    'Perm',
    'Orenburg',
    'Ulyanovsk',
    'Ivanovo',
    'Ryazan',
    'Tolyatti',
    'Kaliningrad',
    'Kursk',
    'Bryansk',
    'Magnitogorsk',
    'Kaluga',
    'Tula',
    'Sochi',
    'Yaroslavl',
    'Ulan-Ude',
    'Tver',
    'Stavropol',
    'Irkutsk',
    'Tiruppur',
    'Sangli',
    'Thoothukudi',
    'Nagercoil',
    'Salem',
    'Tirunelveli',
    'Thanjavur',
    'Mysuru',
    'Tirupati',
    'Patiala',
    'Ajmer',
    'Sagar',
    'Hapur',
    'Shivamogga',
    'Rourkela',
    'Palakkad',
    'Anantapur',
    'Vizianagaram',
    'Etawah',
    'Bhind',
    'Amroha',
    'Alappuzha',
    'Bardhaman',
    'Bhagalpur',
    'Durg',
    'Erode',
    'Kollam',
    'Mathura',
    'Pondicherry',
    'Rajahmundry',
    'Rohtak',
    'Shillong',
    'Shimoga',
    'Silchar',
    'Sonipat',
    'Tuticorin',
    'Udupi',
    'Baramati',
    'Beed',
    'Bhadravati',
    'Bhilwara',
    'Bhusawal',
    'Bidar',
    'Bilaspur',
    'Chandrapur',
    'Chitradurga',
    'Davangere',
    'Dhule',
    'Eluru',
    'Erode',
    'Gadag',
    'Gandhinagar',
    'Godhra',
    'Gulbarga',
    'Hassan',
    'Hospet',
    'Hubli',
    'Haldia',
    'Junagadh',
    'Karimnagar',
    'Karnal',
    'Khanna',
    'Kharagpur',
    'Kottayam',
    'Kollam',
    'Kakinada',
    'Kadapa',
    'Kishangarh',
    'Kollam',
    'Kottayam',
    'Kurnool',
    'Latur',
    'Machilipatnam',
    'Madanapalle',
    'Mandi',
    'Mangaluru',
    'Muzaffarpur',
    'Nadiad',
    'Nagercoil',
    'Nalgonda',
    'Nellore',
    'Ongole',
    'Palghar',
    'Patiala',
    'Pathankot',
    'Pollachi',
    'Proddatur',
    'Pudukkottai',
    'Rajahmundry',
    'Ramanathapuram',
    'Ratlam',
    'Rewa',
    'Rishikesh',
    'Roorkee',
    'Sagar',
    'Satara',
    'Shivpuri',
    'Sikar',
    'Sirsa',
    'Sitapur',
    'Sivakasi',
    'Sri Ganganagar',
    'Srikakulam',
    'Tanjore',
    'Tiruchengode',
    'Tirupati',
    'Tirupur',
    'Tiruvannamalai',
    'Trichy',
    'Vellore',
    'Veraval',
    'Vijayanagaram',
    'Vijayapura',
    'Vizianagaram',
    'Wardha',
    'Yamunanagar',
    'Yavatmal',
    'Zirakpur',
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Autocomplete<String>(
            optionsBuilder: (TextEditingValue textEditingValue) {
              if (textEditingValue.text == '') {
                return const Iterable<String>.empty();
              }
              return options.where((String option) {
                return option.contains(textEditingValue.text.toLowerCase());
              });
            },
            onSelected: (String selection) {
              Navigator.push(context, MaterialPageRoute(
                builder: (context) {
                  return HomePage(
                    cityName: selection,
                  );
                },
              ));

              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text(selection),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

/* ******************************************
*********************************************
*********************************************
              *** END***
*********************************************
*********************************************
****************************************** */
